version: "3.9"
   
services:
  rd-queue:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py seed && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - rd-queue
      - web
